-- SQL Minor Project: Bike Store & Airbnb Analysis - COMPLETE SOLUTION
-- All 5 tasks for BOTH Option 1 (Bike Store) AND Option 2 (Airbnb)
-- Uses only JOINs, GROUP BY, aggregations, ORDER BY. No subqueries/CTEs/LIMIT.

-- =======================================
-- OPTION 1: Bike Store Sales & Inventory Analysis
-- =======================================

-- Task 1: Store Performance – Total revenue generated by each store.
SELECT 
    s.store_name,
    ROUND(SUM(oi.quantity * p.list_price * (1.0 - COALESCE(oi.discount, 0))), 2) AS total_revenue
FROM stores s
INNER JOIN orders o ON s.store_id = o.store_id
INNER JOIN order_items oi ON o.order_id = oi.order_id
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY s.store_id, s.store_name
ORDER BY total_revenue DESC;

-- Task 2: Product Popularity – Top 5 most sold products by quantity.
SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold,
    COUNT(oi.order_id) AS total_orders
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC, total_orders DESC;

-- Task 3: Customer Location – Customers who placed orders with store names.
SELECT 
    c.first_name || ' ' || c.last_name AS customer_name,
    c.city AS customer_city,
    c.state AS customer_state,
    s.store_name AS store_name
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN stores s ON o.store_id = s.store_id
ORDER BY customer_name, store_name;

-- Task 4: Brand Insights – Total number of products per brand.
SELECT 
    b.brand_name,
    COUNT(p.product_id) AS total_products,
    COUNT(DISTINCT p.category_id) AS unique_categories
FROM brands b
INNER JOIN products p ON b.brand_id = p.brand_id
GROUP BY b.brand_id, b.brand_name
ORDER BY total_products DESC;

-- Task 5: Low Stock Alert – Products with zero quantity in stock.
SELECT 
    p.product_name,
    b.brand_name,
    s.store_name,
    COALESCE(st.quantity, 0) AS stock_quantity
FROM products p
INNER JOIN brands b ON p.brand_id = b.brand_id
INNER JOIN stocks st ON p.product_id = st.product_id
INNER JOIN stores s ON st.store_id = s.store_id
WHERE COALESCE(st.quantity, 0) = 0
ORDER BY p.product_name, b.brand_name, s.store_name;

-- =======================================
-- OPTION 2: Airbnb Hospitality & Booking Trends
-- =======================================

-- Task 1: Host Success – Superhosts and total bookings received.
SELECT 
    h.host_name,
    CASE WHEN h.superhost = 'true' THEN 'Superhost' ELSE 'Regular Host' END AS host_type,
    COUNT(DISTINCT f.booking_id) AS total_bookings,
    COUNT(DISTINCT f.property_id) AS properties_hosted
FROM dim_host h
INNER JOIN fact_bookings f ON h.host_id = f.host_id
INNER JOIN dim_property p ON f.property_id = p.property_id
GROUP BY h.host_id, h.host_name, h.superhost
ORDER BY total_bookings DESC;

-- Task 2: Property Revenue – Revenue by property type.
SELECT 
    p.property_type,
    COUNT(DISTINCT f.property_id) AS total_properties,
    ROUND(SUM(f.revenue), 2) AS total_revenue,
    ROUND(AVG(f.revenue), 2) AS avg_revenue_per_booking,
    SUM(f.nights_booked) AS total_nights
FROM dim_property p
INNER JOIN fact_bookings f ON p.property_id = f.property_id
GROUP BY p.property_type
ORDER BY total_revenue DESC;

-- Task 3: Guest Demographics – Average booking price by age group.
SELECT 
    CASE 
        WHEN c.age BETWEEN 18 AND 25 THEN '18-25'
        WHEN c.age BETWEEN 26 AND 35 THEN '26-35'
        WHEN c.age BETWEEN 36 AND 50 THEN '36-50'
        WHEN c.age > 50 THEN '50+'
        ELSE 'Unknown'
    END AS age_group,
    COUNT(DISTINCT f.booking_id) AS total_bookings,
    ROUND(AVG(f.revenue), 2) AS avg_booking_price,
    ROUND(AVG(f.nights_booked), 1) AS avg_nights
FROM dim_customer c
INNER JOIN fact_bookings f ON c.customer_id = f.customer_id
GROUP BY 
    CASE 
        WHEN c.age BETWEEN 18 AND 25 THEN '18-25'
        WHEN c.age BETWEEN 26 AND 35 THEN '26-35'
        WHEN c.age BETWEEN 36 AND 50 THEN '36-50'
        WHEN c.age > 50 THEN '50+'
        ELSE 'Unknown'
    END
ORDER BY avg_booking_price DESC;

-- Task 4: Booking Origins – Total bookings by nationality.
SELECT 
    c.nationality,
    COUNT(f.booking_id) AS total_bookings,
    COUNT(DISTINCT c.customer_id) AS unique_customers,
    ROUND(SUM(f.revenue), 2) AS total_revenue
FROM dim_customer c
INNER JOIN fact_bookings f ON c.customer_id = f.customer_id
GROUP BY c.nationality
ORDER BY total_bookings DESC;

-- Task 5: Rating Analysis – Properties with average rating above 4.5.
SELECT 
    p.property_name,
    p.property_type,
    p.location_city,
    p.location_country,
    ROUND(AVG(f.rating), 2) AS avg_rating,
    COUNT(f.booking_id) AS total_reviews
FROM dim_property p
INNER JOIN fact_bookings f ON p.property_id = f.property_id
WHERE f.rating IS NOT NULL
GROUP BY p.property_id, p.property_name, p.property_type, p.location_city, p.location_country
HAVING AVG(f.rating) > 4.5
ORDER BY avg_rating DESC, total_reviews DESC;

-- =======================================
-- PROJECT NOTES
-- =======================================
-- Bike Store: Assumes standard BikeStore schema (store_id, order_id, product_id, etc.)
-- Airbnb: Uses star schema (fact_bookings → dim_property, dim_host, dim_customer)
-- All queries use multi-table INNER JOINs with GROUP BY aggregations
-- Column aliases (AS) used throughout for clarity
-- ORDER BY DESC on key metrics for business reporting
-- COALESCE handles NULL discounts/ratings/stocks appropriately
-- Ready for single .sql file submission

